# Generated by Django 3.2.12 on 2022-02-05 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A2M/ALK', max_length=50)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('space', models.PositiveBigIntegerField()),
            ],
        ),
    ]
